package.json

Provide more keywords in package.json to improve search on marketplace

---

src/extension/extension.ts

Docker
slightly better but the error message in case of missing docker on system path will be very slightly better only as there will be an ENOENT error. Familiar to JavaScript/TypeScript developer but not all users. To be improved later on.
fixes #38 (we can surely do better but I think we can keep it for another iteration and another issue)
I simulated missing docker by renaming in my dev environment to "plop", so you can remove "plop" by "docker" in the image to have an idea on how it will look alike:

Improve message in case of error when starting the Kaoto backend with

---

package.json
src/extension/extension.ts

Remove reference to kieKogito in naming of Kaoto view

---

package.json

Fixes https://github.com/KaotoIO/vscode-kaoto/issues/39

Enable debugging breakpoint by generating source maps

---

.github/dependabot.yml

following recommendation on
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#example-dependabotyml-file-for-github-actions
fixes #22

ci: provide dependabot config for GitHub Actions

---

.gitignore
.vscode/launch.json
.vscode/tasks.json
CONTRIBUTING.md
README.md
USAGE_DATA.md
package.json
resources/test.kaoto.yaml
src/extension/extension.ts
src/extension/extensionWeb.ts
webpack.config.js
yarn.lock

followed documentation from
https://github.com/redhat-developer/vscode-redhat-telemetry#how-to-use-this-library
currently tracking only generic data on activation and deactivation of the extension
fixes #25
next interesting thing to track:
- opening of the Kaoto editor https://github.com/KaotoIO/vscode-kaoto/issues/55

feat: Include opt-in Red Hat telemetry

---

package.json
yarn.lock

requires https://github.com/KaotoIO/vscode-kaoto/pull/62
fixes #63

63 align pattern fly

---

CONTRIBUTING.md

fixes #13
based on https://github.com/KaotoIO/vscode-kaoto/pull/50

13 improve contributing guide

---

.github/workflows/main-kaoto.yaml
CONTRIBUTING.md
package.json
src/webview/KaotoEditorEnvelopeApp.ts
tsconfig.json
webpack.config.js
yarn.lock

requires https://github.com/KaotoIO/kaoto-ui/pull/916
fixes #66
at same time I had to change the webpack config and remove dependency to @patternfly/patternfly to fix compilation of main branch
(the 2 changes are required to have the main branch compiling)

Change dependency name from kaoto-ui to @kaoto/kaoto-ui

---

.github/workflows/main-kaoto.yaml
CONTRIBUTING.md
README.md
package.json
src/extension/extension.ts
tsconfig.json
yarn.lock

requires https://github.com/KaotoIO/vscode-kaoto/pull/67
fixes #65

65 use released kaoto version

---

.github/workflows/ci.yaml

fixes #1
requires https://github.com/KaotoIO/vscode-kaoto/pull/68

Provide GitHub Workflow using released version of kaoto-ui

---

.github/workflows/ci.yaml
.github/workflows/main-kaoto.yaml
.gitignore
.vscodeignore
CONTRIBUTING.md
it-tests/BasicFlow.test.ts
package.json
test Fixture with speci@l chars/empty.kaoto.yaml
tsconfig.it-tests.json
tsconfig.json
yarn.lock

fixes #7
requires https://github.com/KaotoIO/vscode-kaoto/pull/32

Providing initial test

---

README.md

Specify current limitations in readme

---

it-tests/BasicFlow.test.ts
package.json
test Fixture with speci@l chars/empty.kaoto.yaml
yarn.lock

- updated test to cover case of integration name different than default
fixes #76

Update to Kaoto UI 0.4.3

---

.github/workflows/ci.yaml
README.md
scripts/postinstall.js
src/extension/extension.ts

fixes #88 
based on https://github.com/KaotoIO/vscode-kaoto/pull/85 for simplicity of future rebase

Support MacOS

---

README.md

text from kaoto.io homepage:
https://github.com/KaotoIO/kaoto.io/blob/bd0f34d4d9817b5a0edbf775c9fbaa5b677ab240/data/homepage.yml#L10
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

Including description of Kaoto in Readme

---

.github/workflows/ci.yaml
CHANGELOG.md
README.md
package.json
scripts/postinstall.js
yarn.lock

requires release of Kaoto UI 0.5.0

chore(deps): Upgrade Kaoto UI to 0.5.0 and backend to 0.5.1

---

package.json
webpack.config.js
yarn.lock

required with latest version of Kaoto UI
fixes #133

Add constants-browserify to webpack fallback

---

CONTRIBUTING.md
src/extension/extension.ts

Provide how to use a different Kaoto backend during development

---

CHANGELOG.md
README.md
package.json
scripts/postinstall.js
yarn.lock

fixes #166
fixes #158
fixes #145
fixes #132

Upgrade Kaoto to 0.7.1

---

CHANGELOG.md
README.md
package.json
scripts/postinstall.js
yarn.lock

Upgrade embedded Kaoto to 0.7.3

---

it-tests/BasicFlow.test.ts
it-tests/Util.ts

Recalculate WebView between attempts of switchToFrame and hard sleep waiting for VS Code initialization

---

CHANGELOG.md
README.md
it-tests/BasicFlow.test.ts
it-tests/ContextualMenuOpen.test.ts
it-tests/Util.ts
package.json
src/extension/extension.ts
test Fixture with speci@l chars/my.yaml

Provide contextual menu to open yaml files with Kaoto

---

CHANGELOG.md
README.md
package.json
scripts/postinstall.js
yarn.lock

Upgrade embedded Kaoto to 0.7.5

---

CHANGELOG.md
README.md
package.json
scripts/postinstall.js
yarn.lock

Upgrade embedded Kaoto to 0.7.6

---

CHANGELOG.md
README.md
package.json
scripts/postinstall.js
yarn.lock

Upgrade embedded Kaoto to 1.0.0-rc1

---

webpack.config.js

This is the counterpart of the [UI pull request](https://github.com/KaotoIO/kaoto-ui/pull/1692)
relates: KaotoIO/kaoto-ui#696

feat(vscode): Provide KaotoUI version

---

it-tests/BasicFlow.test.ts
it-tests/ContextualMenuOpen.test.ts
it-tests/StepExtensionLoading.test.ts
it-tests/Util.ts
package.json

EDIT:
- without this PR the tests failures are in place almost for each run
- with these changes the port in use issue is gone and also context menu item issue ia fixed

Improve GH actions workflow tests stability

---

Jenkinsfile

it will require also https://gitlab.cee.redhat.com/codeready-studio/cci-config/-/merge_requests/744
On the PR on CCI Config, i have not added Ricardo as he was already in the list

Update list of approvers for the release on Jenkins

---

it-tests/BasicFlow.test.ts
package.json
yarn.lock

- update to Kaoto 0.7.0
- bump ExTester to latest version
- small fix for BasicFlow test on L128

Re-enable check for integration name in top bar dropdown

---

it-tests/SwitchBetweenTabs.test.ts

https://issues.redhat.com/browse/FUSETOOLS2-2271

Add initial tests for switching between editor tabs

---

package.json

Remove no more needed activation event

---

src/webview/KaotoEditorEnvelopeApp.ts

Remove keyboard shortcut icon

---

Jenkinsfile

job using branch from this PR in success storing the manifest https://studio-jenkins-csb-codeready.apps.ocp-c1.prod.psi.redhat.com/job/Fuse/job/VSCode/job/vscode-kaoto-release/196/

FUSETOOLS2-2277 - generate sbom on Jenkins and archive it

---

CHANGELOG.md
README.md
package.json
yarn.lock

requires https://github.com/KaotoIO/vscode-kaoto/pull/477 and https://github.com/KaotoIO/vscode-kaoto/pull/475

Upgrade to 2.0.0-TP1.2

---

README.md

issue-463: Add a badge to show the kaoto version

---

src/extension/helpers.ts

feat: simplify glob pattern for files supported by Kaoto

---

package.json
webpack.config.js
yarn.lock

Remove workaround for patternfly react topology during build

---

.github/workflows/main-kaoto.yaml
CHANGELOG.md
CONTRIBUTING.md
README.md
package.json
src/webview/KaotoEditorEnvelopeApp.ts
webpack.config.js
yarn.lock

it contains change of package name
fixes #559

Upgrade to Kaoto 2.0.0 TP3.1

---

CHANGELOG.md
it-tests/OpenTextualEditorCommand.test.ts
package.json
src/extension/extension.ts

Provide command to open textual editor to the side

---

.vscode/launch.json
CHANGELOG.md
src/extension/extensionWeb.ts

Fix getCatalogUrl missing API in web version

---

CHANGELOG.md
src/extension/extensionWeb.ts

based on https://github.com/KaotoIO/vscode-kaoto/pull/640

482 fix open with kaoto editor in web version

---

package.json
yarn.lock

Previous version comes through transitive dependencies with a version containing CVE

Ensure dset 3.1.4+ is used

---

src/webview/VSCodeKaotoEditorChannelApi.ts

Implement deleteResource ChannelEditor API

---

.gitignore
.vscodeignore

there is no reason to include them in the generated vsix

Add Camel Jbang and .idea to vscode ignore

---

.github/dependabot.yml

Allow more dependabot PRs and increase number of dependencies that must

---

CONTRIBUTING.md
Jenkinsfile

migration to a new Jenkins instance

ci: migration to a new Jenkins instance

---

it-tests/BasicFlow.test.ts
it-tests/settings/NodeLabelSettings.test.ts

fixing test with main branch of Kaoto

Adapt UI test to new attributes

---

src/extension/ExtensionContextHandler.ts
src/views/providers/HelpFeedbackProvider.ts

fix: custom icons are not properly displayed for web extension bundle in Help & Feedback view 

---

package.json

feat: sort out user settings into sub categories

---

.github/workflows/ci.yaml
.github/workflows/main-kaoto.yaml
CHANGELOG.md
README.md
it-tests/views/IntegrationsViewNewFile.test.ts
package.json
src/commands/AbstractCamelCommand.ts
src/commands/AbstractNewCamelRouteCommand.ts
src/commands/NewCamelKameletCommand.ts
src/commands/NewCamelPipeCommand.ts
src/commands/NewCamelRouteCommand.ts
src/extension/ExtensionContextHandler.ts
src/extension/extension.ts
src/extension/extensionWeb.ts
src/helpers/CamelJBang.ts
src/helpers/ClasspathRootFinder.ts
src/helpers/helpers.ts
src/tasks/CamelBindJBangTask.ts
src/tasks/CamelInitJBangTask.ts
src/tasks/CamelJBangTask.ts
src/test/ClasspathRootFinder.test.ts
src/webview/VSCodeKaotoEditorChannelApi.ts
yarn.lock

Supports
- Routes, Pipes and Kamelets YAML DSL
- single workspace folder
- multi workspace folders

feat: add New Camel File... button into Kaoto: Integrations view

---

.github/workflows/ci.yaml
.github/workflows/main-kaoto.yaml
CHANGELOG.md
src/extension/ExtensionContextHandler.ts
src/extension/extension.ts
src/helpers/helpers.ts

added info message for user into Kaoto Output Channel

feat: add Apache Camel trusted source check

---

src/helpers/helpers.ts

fix: promisify error blocks activation in web extension

---

package.json
src/extension/ExtensionContextHandler.ts
src/helpers/modals.ts

Context Menu options
- delete file
- show source

feat: add right-click options for each file item in Kaoto: Integrations view

---

CHANGELOG.md
USAGE_DATA.md
src/extension/ExtensionContextHandler.ts
src/extension/extension.ts
src/extension/extensionWeb.ts

sending event into RH Telemetry plugin about
- file creation: Route, Pipe, Kamelets
- open with kaoto editor
- show/close source (toggle button)
- show source and delete (right-click menu items)

chore: add events for Red Hat Telemetry about commands usage

---

CHANGELOG.md
README.md
it-tests/Z_IntegrationsViewNewProject.test.ts
package.json
src/commands/NewCamelProjectCommand.ts
src/extension/ExtensionContextHandler.ts
src/helpers/CamelJBang.ts
src/helpers/helpers.ts
src/helpers/modals.ts
src/tasks/CamelExportJBangTask.ts

https://github.com/user-attachments/assets/a0215d11-ada8-452b-88fd-42a1d3991411

feat: add export inline button into Kaoto: Integrations view

---

Jenkinsfile

- run UI tests against prebuilt VSIX which is then going to be published
- unblocks Kaoto release jenkins job - https://jenkins-csb-fusetools-qe-master.dno.corp.redhat.com/job/vscode/job/eng/job/vscode-kaoto-release/141/

chore: Update Jenkinsfile to run tests with prebuilt VSIX which is going to be published

---

it-tests/views/IntegrationsViewNewFile.test.ts

will unblock build with Kaoto main branch job

fix: rework UI tests to support latest Kaoto XML changes

---

webpack.config.js

This is a prerequisite of: https://github.com/KaotoIO/kaoto/pull/2083/files
fix: https://github.com/KaotoIO/kaoto/issues/997

feat(About): Define VSCODE_KAOTO_VERSION

---

it-tests/SwitchBetweenTabs.test.ts

to unblock build with a main kaoto branch

fix(test): remove Kaoto UI tabs precise number check

---

src/extension/ExtensionContextHandler.ts
src/helpers/CamelJBang.ts
src/tasks/CamelKubernetesRunJBangTask.ts
src/tasks/CamelRunJBangTask.ts

fix: web extension failed to load in a browser

---

CHANGELOG.md
README.md
it-tests/BasicFlow.test.ts
it-tests/views/IntegrationsView.test.ts
it-tests/views/IntegrationsViewNewFile.test.ts
package.json
src/commands/AbstractCamelCommand.ts
src/commands/NewCamelFileCommand.ts
src/commands/NewCamelRouteCommand.ts
src/extension/ExtensionContextHandler.ts
src/helpers/helpers.ts
src/views/providers/IntegrationsProvider.ts
src/views/providers/integrationTreeItems/Integration.ts
test Fixture with speci@l chars/kaoto-view/kaoto.camel.xml
test Fixture with speci@l chars/kaoto-view/sample.camel.xml

feat: add support for XML files

---

CHANGELOG.md
it-tests/default/extension.test.ts
package.json
src/extension/ExtensionContextHandler.ts
src/extension/extension.ts
test Fixture with speci@l chars/.vscode/settings.json
yarn.lock

EDIT:
Using `@redhat-developer/vscode-extension-proposals`:
Note: not working for Web Kaoto version

feat: show recommended extensions notification

---

src/helpers/ApplicationPropertiesFinder.ts
src/helpers/SuggestionRegistry.ts
src/test/webview/suggestionProviders.test.ts
src/webview/VSCodeKaotoEditorChannelApi.ts

instead of duplicating and redeclaring it in VS Code Kaoto
fixes #975

Use Suggestion* types defined in Kaoto forms

---

it-tests/BasicFlow.test.ts
it-tests/MavenDependencyUpdate.test.ts
it-tests/Util.ts
package.json
src/webview/KaotoEditorEnvelopeApp.ts
src/webview/envelope-overrides/KogitoEditorEnvelope.tsx
src/webview/envelope-overrides/KogitoEditorEnvelopeApp.tsx
src/webview/envelope-overrides/envelope-init.ts
yarn.lock

Based on #1078 initial work of @lordrip which was closed because of UI tests instability.

feat(KIE): Override KIE KogitoEditorEnvelope

---

CHANGELOG.md
package.json

Fix link to documentation to generate catalog

---

CHANGELOG.md
it-tests/MavenDependencyUpdate.test.ts
it-tests/Util.ts
package.json
src/extension/ExtensionContextHandler.ts
src/helpers/StepsOnSaveManager.ts

feat: allow users execute Camel dependency update manually

---

.github/workflows/test-snapshot.yaml
it-tests/01_env/check.camel.version.ts
it-tests/01_env/set.camel.version.ts
it-tests/Util.ts
package.json

workflow runs here - https://github.com/KaotoIO/vscode-kaoto/actions/workflows/test-snapshot.yaml

chore: enable run tests with Camel JBang snapshot version
