KaotoIO/vscode-kaoto

package.json
src/extension/extension.ts

sync up references between internal and various place in package.json
and simplify name to avoid redundant VS Code mention in the Display name
fixes #10
fixes #12

Update publisher and vs code id

---

.github/workflows/main-kaoto.yaml

Advantages:
- detect very early if there are incompatibilities with upcoming version
- unblock situation until there is a release. Will be able to continue work to provide a test for instance. And to have a binary available for manual local testing
- after first release of kaoto-ui, the part
```
cp package.json package.json.bak
sed -i '/kaoto-ui/d' package.json
yarn
cp -f package.json.bak package.json
yarn link kaoto-ui
```
can be reduced to:
```
yarn
yarn link kaoto-ui
```
it will allow to launch it on MacOS and Windows
fixes #35

Provide job using main kaoto-ui

---

src/extension/extension.ts

latest tag
using main tag
It remains up to the end-user to update their local image of main. Until there is tagged version of kaoto-ui, I think it is better to use this one. It might break but at least it will allow to detect it sooner.

The current kaoto-ui main branch requires a more recent backend than the

---

package.json

It will mitigate the case of Kaoto backend not yet ready when opening a Kaoto file.
Previously, it was starting it only when the Kaoto editor was opened. Now it is starting when it detects a Kaoto file in workspace or when all other extensions with high priority have activated.
fixes #34
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

Start docker image sooner

---

README.md
it-tests/BasicFlow.test.ts
src/extension/extension.ts

fixes #82
- it is a lot faster, especially the very first startup!
- same limitations than before with Docker images
- ninary is currently pushed, will  be improved with #84

Use native library for Linux AMD 64 instead of Docker image

---

.github/workflows/ci.yaml
.github/workflows/main-kaoto.yaml

it also avoids to use deprecated API of GitHub Action from transitive dependency

Simplify xvfb config in GitHub Workflow

---

CONTRIBUTING.md
Jenkinsfile

part of #4
works with https://gitlab.cee.redhat.com/codeready-studio/cci-config/-/merge_requests/653
~~The job was working with locally built Jenkins instance but I'm unable to restart it. I stopped ti to have a completely clean one. So cannot show proof it is working :'-(~~
Can be seen here http://10.39.192.130:8080/job/Fuse/job/VSCode/job/vscode-kaoto-release/1/ (with Red Hat VPN and as long as I keep the instance running on my local machine). the job parameters has been slightly modified to be able to run. We will need this branch to be merged before it works on official jenkins. 
it is mostly aligned from VS Code Yaml https://github.com/redhat-developer/vscode-yaml/blob/main/Jenkinsfile . the difference is that I removed the pre-release part as [it is not …

Provide Jenkins job config to publish a release

---

CHANGELOG.md
package.json

the 0.1.0 cannot be pushed to Microsoft Marketplace due to previous issue during development. Upgrading to 0.2.0 and will do a release with 0.2.0

Upgrading version to 0.2.0

---

CHANGELOG.md
src/extension/extension.ts

native executable cannot be launched.
It allows to have more information what can be the issue.
for instance, when the port is already occupied:

feat: Keep `Kaoto backend` output log available when Kaoto backend

---

Jenkinsfile

RHEL 8 is no more working as glibc 2.32 seems to be required by Kaoto Backend 0.6.1

Use RHEL 9 for JenkinsFile

---

.github/workflows/ci.yaml

it is failing 9 out of 10 times with MacOS 12
fixes #122

Test with MacOS 11

---

CHANGELOG.md
README.md
scripts/postinstall.js

fixes #128
fixes #126 
it introduces long delay to add a step #132 but it avoids infinite loop of #126 so i guess, it become a slightly better state if merging

Upgrade to Kaoto Backend 0.6.2

---

.github/dependabot.yml

update automatically only the dependencies which does not need to be in sync with Kaoto UI
fixes #48

Provide dependabot config for dependencies

---

CHANGELOG.md
README.md
it-tests/BasicFlow.test.ts
package.json
src/extension/extension.ts
test Fixture with speci@l chars/my.camel.yaml

Open *.camel.(yaml|yml) files by default with kaoto editor

---

CHANGELOG.md
package.json
src/extension/extension.ts
yarn.lock

The problem is that if the catalogs are not warmed up on first requests from kaoto UI, the content is wiped out because Kaoto backend seems to not waiting for the Catalog to be warmed up before returning an answer and consequently it is providing an empty results as it knows nothing of the content.
Not found an easy way to provide a non-regression test as it requires a restart of VS Code (but maybe we can find some alternatives, reload of workspaces/resources? the thing is that it requires the extension to be deactivated and reactivated so that the kaoto backend shut down) reported #147 - In fact, by side effect,  in case of regression it fails because it will cause curren tUi tests to fail with a timeout. It will be the case if they stay with a timeout which is lower than the tiemout …

Avoid wipeout of content on restart with opened editors

---

CHANGELOG.md
README.md
package.json
scripts/postinstall.js
yarn.lock

it requires to align patternfly dependency
fixes #131
fixes #135 - patternfly must be aligned, the order of parameters of one method has been reversed and so the two versions are not compatible. fixes #149 - not found the reason why the branching is working with latest version but I suspect similar root cause of not aligned patternfly version

Upgrade to Kaoto 0.7.0

---

it-tests/BasicFlow.test.ts
it-tests/StepExtensionLoading.test.ts
it-tests/Util.ts
package.json
test Fixture with speci@l chars/choice.camel.yaml
webpack.config.js

the trick is that the libraries were not visible to Step Extensions
because it is using micro-frontend patterns an it requires module
federation.
This commit is picking all dependencies and using them in federated
module with an `eager` state to true. This is not optimal. it can
potentially cause performance issue but none are visible currently (and
at least it is still better than crashing the editor when there is the
need for a step extension)
fixes https://github.com/KaotoIO/vscode-kaoto/issues/157
note: need to enclose the glob pattern for launching multiple tests

Fix step extension loading

---

src/extension/extension.ts

it will avoid this kind of message on the sameline:
`Kaoto backend process closed with code: 1Kaoto backend is stopped during VS Code extension deactivation.`

Provide return to line after logging messages

---

test Fixture with speci@l chars/.vscode/settings.json

the goal is to avoid this kind of notifications: ![Kaoto basic development flow Open empty camel yaml file, check Kaoto UI is loading, add a step and save](https://user-images.githubusercontent.com/1105127/225673979-3098afe6-5419-4802-8b1b-6445e524e14a.png)

Stabilize tests by avoiding some notifications popup

---

.github/workflows/ci.yaml

currently 12 instead of 11.
It should be more stable now after other improvements
fixes #125

Launch test on CI on MacOS latest

---

CHANGELOG.md
CONTRIBUTING.md
README.md
src/extension/extension.ts
webpack.config.js

8081 port is the default one for Quarkus applications causing often port conflicts.
To mitigate this problem changed the port to 8097.
plan is to pick a free port dynamically in another iteration, see #60 
fix #253

Change port of embedded Kaoto backend to 8097

---

CHANGELOG.md
README.md
scripts/postinstall.js

Despite new backend 1.0.1 and the v2 endpoints, the UI tests are not passing with main branch of Kaoto UI.
I think they need to be adapted as the dom has been surely modified for some pieces.
We can still merge the backend upgrade, it will help to work on adapting the test to new UI from main branch to prepare later integration of next release

Upgrade kaoto backend to 1.0.1

---

.github/workflows/ci.yaml
.github/workflows/main-kaoto.yaml
.vscodeignore
CONTRIBUTING.md
Jenkinsfile
package.json
webpack.config.js
yarn.lock

- not using `yarn pack:prod` as finer grained is required with JenkinsFile
- adapted GitHub Actions to be as close as possible as JenkinsFile
fixes #187
It allows a size reduction of packed vsix from 244.3Mo to 104.5Mo

Do not embed node_modules in vsix

---

webpack.config.js

keeping the old way too as it is not part of a released version yet
relates to KaotoIO/kaoto-standalone#32

Adapt way to provide KAOTO_API url

---

src/extension/extension.ts

With the recent upgrade from Kaoto Backend to Quarkus 3.2, it seems that now the CORS configuration are more restricted.
The fix is to allow origins from the `vscode-webview://` schema
1. Download the pull request branch
2. Update the backend version to at least `v1.1.0-M2`
3. Run the extension, the UI should load properly

fix(backend): Fix Kaoto backend CORS issues

---

.github/workflows/main-kaoto.yaml
CONTRIBUTING.md

After `kaoto-ui` repository turned into a `monorepo`, we need to update the command used to link the `vscode-kaoto` repository and the `kaoto-ui` one.
Relates to this pull request: https://github.com/KaotoIO/kaoto-ui/pull/2158
fixes: https://github.com/KaotoIO/kaoto-ui/issues/2159

chore: Incorporate kaoto-ui monorepo changes

---

scripts/postinstall.js

Before
- we spotted situation when there was missing backend binary for windows architecture and it lead to invisible flakiness because inside binaries of vscode kaoto extension the `kaoto-windows-amd64.exe` existed, but it was just created by our code and empty
After
- there will be from now check and error thrown when url we are trying to reachout with backend binaries is valid or not
Example of error in case there is not binary file available
```
➤ YN0000: ┌ Resolution step
➤ YN0060: │ @kaoto/kaoto-ui@npm:1.1.0-M3 [9fe6b] provides monaco-editor (p45f69) with version 0.40.0, which doesn't satisfy what react-monaco-editor requests
➤ YN0002: │ @kaoto/kaoto-ui@npm:1.1.0-M3 [9fe6b] doesn't provide prop-types (pefe68), requested by react-router-last-location
➤ YN0060: │ …
```

Throw error when trying to download non existing Kaoto backend binary

---

CHANGELOG.md
README.md
package.json
yarn.lock

After reviewing the list of changes in Kaoto UI, there are:
- hiding of Deploy button all the time
- dependencies upgrade: the only one to align is a maintenance version of @patternfly/react-core
Tested manually locally. Not detected issues.
Risk is low of regressions.
The Kaoto UI changes are independent of Kaoto backend between 1.2 and 1.3 so it is ok to have it in 2 phases

Upgrade embedded Kaoto UI to 1.3.0

---

CHANGELOG.md
README.md
scripts/postinstall.js

to be tested when Kaoto backend 1.3.0 release is done (native binaries published)

Upgrade Kaoto backend from 1.2.0 to 1.3.0

---

.github/workflows/ci.yaml
.github/workflows/main-kaoto.yaml
Jenkinsfile

* Node 16 is EOL
* Newer version of Node 18 are nto working with  vscode-extension-tester

FUSETOOLS2-2176 - upgrade CI to use Node 18.15.x

---

Jenkinsfile

- rhel 9 is configured with ipv6 on jenkins, we need ipv4 so back to rhel 8
- vscode-extension-tester requires Node 18.15.x, we cannot play tests on Jenkins for now. they are played on GitHub Actions
see this build https://studio-jenkins-csb-codeready.apps.ocp-c1.prod.psi.redhat.com/job/Fuse/job/VSCode/job/vscode-kaoto-release/154/ with these modifications

Fix Jenkinsfile for Node 18

---

CHANGELOG.md
src/extension/extension.ts
src/extension/extensionWeb.ts
src/extension/helpers.ts

Fix Kaoto editor in vscode.dev web environment

---

.github/workflows/ci.yaml

Use cdxgen as it is a yarn project, it comes with these limitations compared to other VS code Camel tooling project:
- mix of hierarchical and flat view of dependencies
- dev dependencies are included

FUSETOOLS2-2272 - generate sbom on GitHub Action

---

.github/workflows/ci.yaml
.github/workflows/main-kaoto.yaml

to avoid problems between VS Code extension tester and 1.86.x

Use VS Code 1.85.2 to play UI tests

---

.github/workflows/ci.yaml
.github/workflows/main-kaoto.yaml
CHANGELOG.md
README.md
package.json
yarn.lock

requires https://github.com/KaotoIO/vscode-kaoto/pull/477

Upgrade embedded Kaoto to 2.0.0-TP1.1

---

it-tests/BasicFlow.test.ts
it-tests/PropertyPanelLoading.test.ts
test Fixture with speci@l chars/.vscode/settings.json

- `pf-topology__node__action-icon` is used for the route container actions too, not found a cleaner way for now to pick the second entry in the list
- use replace instead of insert so that the test can work with both released and main branch of kaoto. We do not care in this test where the node is added
- the side panel needs to be awaited to be displayed on all OS now (which seems more coherent)
- added an ugly sleep, not found another way to wait for panel to be closed correctly. It seems like the close button is not ready immediately even if displayed, unless it is it due to animation and the click is sent to the wrong place?
- ignore extension recommendation: it avoids having a notification popup on Windows for Windows Subsystem Linux extension to interfere with the UI tests

chore: adapt UI tests to main branch having route container

---

.github/workflows/ci.yaml
.github/workflows/main-kaoto.yaml

currently it is VS Code 1.86.1, and in future it should be always the latest VS Code verssion which was tested that EWxTester is working with that version

build: Use for testing the latest (max) VS Code version supported by ExTester

---

it-tests/BasicFlow.test.ts

The order in the dom has been modified. A more precise xpath is required.

Adapt test for main branch of Kaoto UI

---

Jenkinsfile

Successful execution with `Test` step - https://studio-jenkins-csb-codeready.apps.ocp-c1.prod.psi.redhat.com/job/Fuse/job/VSCode/job/vscode-kaoto-release/250

build(jenkins): Re-enable tests to run during Jenkins jobs

---

it-tests/BasicFlow.test.ts

Fixes #580 
Because of [this](https://github.com/KaotoIO/kaoto/commit/7277d49aeda6c5acf6cb3779a3e53d922c9715fe) latest change in Kaoto, the Integration tests were failing.  This PR fixes those tests.

fix(test): Updated xpath which points to the correct FlowsMenu HTML element

---

CHANGELOG.md
README.md
it-tests/CatalogURLSettings.test.ts
it-tests/Util.ts
package.json
src/extension/extension.ts
src/webview/KaotoEditorEnvelopeApp.ts
src/webview/VSCodeKaotoChannelApiProducer.ts
src/webview/VSCodeKaotoEditorChannelApi.ts
yarn.lock

Add a ´catalogUrl´ setting to point to a specific kaoto catalog version
In this PR we're updating the ´@kaoto/kaoto´ version to ´2.1.0-RC3´ so we can handle the case of an empty `catalogUrl`

feat(settings): Provide VSCode setting for the `catalogUrl`

---

CHANGELOG.md
README.md
package.json
src/webview/VSCodeKaotoEditorChannelApi.ts
tsconfig.it-tests.json
tsconfig.json
yarn.lock

This commit adds a new `getVSCodeKaotoSettings` method to the `VSCodeKaotoEditorChannelApi` class to build the Settings model.
It also deprecates the existing `getCatalogURL` method as the new way to go is using the settings adapter from now on.
This PR needs to be merged after: https://github.com/KaotoIO/kaoto/pull/1264
relates: https://issues.redhat.com/browse/KTO-441
relates: https://github.com/KaotoIO/kaoto/pull/1221
relates: https://github.com/KaotoIO/kaoto/pull/1264

feat(vscode): Provide SettingsAdapter for VSCode

---

CHANGELOG.md
README.md
it-tests/settings/CatalogURLSettings.test.ts
it-tests/settings/NodeLabelSettings.test.ts
package.json
src/webview/VSCodeKaotoEditorChannelApi.ts
test Fixture with speci@l chars/my.camel.yaml

This commit wires up the `nodeLabel` setting so the user can choose what label a node shows.
relates: https://issues.redhat.com/browse/KTO-441
relates: https://github.com/KaotoIO/kaoto/pull/1221
relates: https://github.com/KaotoIO/kaoto/pull/1264

feat(settings): Wire up `nodeLabel` setting

---

it-tests/PropertyPanelLoading.test.ts

- keep xpath selector `//*[name()='g' and starts-with(@data-testid,'custom-node__when')]` until we have a release of Kaoto with new changes
- requires to 2 div level because the foreignObject and the first div are not clickable Element
fixes #631

Adapt test to container in Kaoto

---

CHANGELOG.md
package.json

fixes #494
Ctrl+k v is the shortcut used to "show preview" in several extensions. To "show source", I found no extensions with a pre-defined shortcut. I think we can reuse it as it is qknd of the "opposite" and the enablement will cover different cases withotu overlapping

Provide keyboard shortcut to open text editor

---

.yarnrc.yml
CHANGELOG.md
README.md
package.json
yarn.lock

Since other consumers need to use `@kaoto/kaoto`, we need to remove as many dependencies as possible from Kaoto itself and provide them as `peerDependencies`.
This PR updates `@kaoto/kaoto` to `2.2.0-RC4` and provides the missing dependencies.

feat(build): Update Kaoto to 2.2.0-RC4

---

CHANGELOG.md
it-tests/OpenTextualEditorCommand.test.ts
package.json

based on https://github.com/KaotoIO/vscode-kaoto/pull/627
fixes #493

493 quick action to opentextual editor to the side

---

src/webview/VSCodeKaotoEditorChannelApi.ts

Required for: https://github.com/KaotoIO/kaoto-datamapper-integration/issues/69

fix(DataMapper): Add workspace file picker hook

---

CHANGELOG.md
src/KaotoOutputChannelManager.ts
src/webview/VSCodeKaotoEditorChannelApi.ts

Use an Output channel to log errors

---

it-tests/settings/NodeLabelSettings.test.ts

it displays now both description or id and the component name, see https://github.com/KaotoIO/kaoto/pull/1560

Adapt UI tests to label modification on Kaoto main branch

---

src/extension/ClasspathRootFinder.ts
src/test/ClasspathRootFinder.test.ts
src/webview/VSCodeKaotoEditorChannelApi.ts

compatible with Maven based projects
basically looking for classpath root src/main/resources if there is some for the xsl file. And using a relative path to the .kaoto file for the xsd file

Change implementation of VS Code Channel editor API to have it

---

it-tests/settings/CatalogURLSettings.test.ts

* SpringBoot renamed to Spring Boot
* Red Hat catalogs are now the first catalog and no more the last
there were these tests on error:
```
1) User Settings
Check custom Kaoto catalog loaded - SpringBoot:
NoSuchElementError: no such element: Unable to locate element: {"method":"xpath","selector":"//li[@data-testid='runtime-selector-SpringBoot']"}
(Session info: chrome=124.0.6367.243)
at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:521:15)
at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:514:13)
at Executor.execute (node_modules/selenium-webdriver/lib/http.js:446:28)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Driver.execute (node_modules/selenium-webdriver/lib/webdriver.js:744:17)
2) User Settings
Select …
```

Adapt test to newly published example of catalog set

---

src/webview/VSCodeKaotoEditorChannelApi.ts

This is an ugly workaround that could lead to path clashes. 2 different APIs must be provided to retrieve content, one relative to classpath root and the other relative to .kaoto metadata file, reported https://issues.redhat.com/browse/FUSETOOLS2-2505

Temporary workaround to get ResourceContent

---

it-tests/BasicFlow.test.ts
it-tests/settings/NodeLabelSettings.test.ts
src/webview/VSCodeKaotoEditorChannelApi.ts

From the Kaoto side, we have default settings in the
[settings.model.ts](https://github.com/KaotoIO/kaoto/blob/9ee3368e0e488853f61a84fa4e16bedadc801fda/packages/ui/src/models/settings/settings.model.ts#L23-L25) file.
This commit uses that and only overrides what needs to be changed in terms of the `catalogUrl` and the `nodeLabel`.
Once the VS Code setting for the new property `nodeToolbarTrigger` is merged, we can add it also to the VS Code settings object.

fix(Settings): Use default Settings from Kaoto

---

package.json
yarn.lock

on other projects it was automatically updated when integrating VS Code Red Hat telemetry with the latest version but not on this one. i do not know why (maybe yarn is not resolving the same way?)

Force cross-spawn 7.0.5+

---

.github/dependabot.yml

given that kaoto moved to Vite instead of webpack

No more need to align webpack with Kaoto

---

CHANGELOG.md
it-tests/BasicFlow.test.ts
src/webview/VSCodeKaotoEditorChannelApi.ts

based on https://github.com/KaotoIO/vscode-kaoto/pull/749
fix #747 
* The fix consists in using fsPath of the vscode.URI
* Added the UI test part to check source xsd correctly loaded
* Note that the contextual menu to delete the step in tests is used
instead of the toolbar (which is more modern) as the delete button
toolbar is not visible enough to be clickable
we can notice that the added test is failing without the fix https://github.com/KaotoIO/vscode-kaoto/pull/750

747 fix: support xsd in Kaoto DataMapper on Windows

---

package.json
yarn.lock

Currently, when building `vscode-kaoto`, there are warnings about `sass-loader` using deprecated APIs.
```
WARNING in ./node_modules/@kie-tools-core/editor/dist/envelope/styles.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./node_modules/@kie-tools-core/editor/dist/envelope/styles.scss)
Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
More info: https://sass-lang.com/d/legacy-js-api
```
The fix is to update `sass-loader` to `v16`

fix(build): Remove sass-loader warnings

---

CHANGELOG.md
package.json
src/webview/VSCodeKaotoEditorChannelApi.ts

feat: Add missing settings to VS Code Kaoto

---

CHANGELOG.md
README.md
package.json
src/views/providers/HelpFeedbackProvider.ts
src/views/providers/IntegrationsProvider.ts
yarn.lock

it will allow to use newer VS Code API for upcoming Kaoto view features

chore: bump minimal supported VS Code from 1.74.0 to 1.95.0

---

package.json

this will handle unsupported Web Browser environments of WEbExtension entry-point. At browser web extension the buttons  like `New File...` which requires JBang (shell execution) wont be visible in UI + there is a warning message which is visible in description of extension in Markeplace. (see https://code.visualstudio.com/api/extension-guides/virtual-workspaces#partial-and-full-support-for-virtual-workspaces)
I have tested locally and behavior is:
- Red Hat Dev Spaces in Browser --> **buttons visible and working**
- Desktop VS Code --> **buttons visible and working**
- VS Code in Browser or GitHub Codespaces --> **buttons not visible**

fix: show warning and hide not supported buttons in virtual workspace web environments

---

CHANGELOG.md
package.json
src/commands/NewCamelFileCommand.ts
src/extension/ExtensionContextHandler.ts

- if no workspace, show Open Folder
- if existing workspace and no camel related files, show New Camel File
NO WORKSPACE
NO CAMEL FILE

feat: add welcome content into Kaoto: Integrations view

---

it-tests/BasicFlow.test.ts
it-tests/ContextualMenuOpen.test.ts
it-tests/OpenTextualEditorCommand.test.ts
it-tests/Util.ts
it-tests/settings/CatalogURLSettings.test.ts
it-tests/settings/NodeLabelSettings.test.ts
it-tests/views/01_KaotoViewBasic.test.ts
it-tests/views/IntegrationsView.test.ts
it-tests/views/IntegrationsViewNewFile.test.ts

Hopefully this will improve the tests were flaky from time to time.

test: add dynamic wait for extension activation after each vscode window reload

---

src/commands/NewCamelProjectCommand.ts
src/test/ValidateNewProjectGAV.test.ts

from now it should be more compliant with common maven project conventions for GAV
groupId - The is expected to follow the Java package naming conventions
artifactId - The identifiers should only consist of lowercase letters, digits, and hyphens
version - The version is expected be compliant with Semantic Versioning 1.0.0

fix: improve regex for a GAV validation of new project creation process

---

src/helpers/CamelJBang.ts

we need to search xsl files in current folder of running integration file instead of always searching whole workspace

fix: respect parent folder of the running integration when looking for existing xsl files

---

it-tests/BasicFlow.test.ts

The ActiveMQ component is part only of the community catalog. The new default catalog is a productized one, see https://github.com/KaotoIO/kaoto/issues/1955
Updated test to use amqp instead of ActiveMQ.

Adapt test to change of default catalog in Kaoto main branch to fix build with main Kaoto

---

it-tests/Z_IntegrationsViewNewProject.test.ts

in some cases there is test still failing because of another button, depending probably on platform, localization and others to ensure well formatted path inside input box

test: fix unstable export project UI test mainly on macOS

---

src/tasks/CamelRunJBangTask.ts
src/views/deploymentTreeItems/ParentItem.ts
src/views/providers/DeploymentsProvider.ts

the current behavior is wrong because when you run same integration multiple times it will merge all routes under one integrations which is not right
BEFORE:
---
after this change it behaves as `camel run` itself. Camel JBang allows you to run more times same integrations, each is run with unique PID. In VS Code instead of PID we are atm binding to a console port which is generated unique for each run through UI
AFTER:
also adding a path of an associated running integration file into hover

fix: allow to run integrations with a same name simultaneously

---

CHANGELOG.md
it-tests/views/06_DeploymentsViewLogsAndStop.test.ts
package.json
src/extension/ExtensionContextHandler.ts
src/helpers/CamelJBang.ts
src/tasks/CamelStopJBangTask.ts

adding `Stop` and `Follow Logs` buttons
REPORTED upstream issue - https://issues.apache.org/jira/browse/CAMEL-21921

feat: add Stop and Logs action buttons into Kaoto: Deployments view

---

CHANGELOG.md
it-tests/views/07_DeploymentsViewRoutesManipulaton.test.ts
package.json
src/extension/ExtensionContextHandler.ts
src/helpers/CamelJBang.ts
src/tasks/CamelRouteOperationJBangTask.ts
src/views/deploymentTreeItems/ChildItem.ts
src/views/providers/DeploymentsProvider.ts

feat: add start/stop/resume/suspend buttons on a 'route' level in Deployments view

---

.github/dependabot.yml
package.json
yarn.lock

those monaco-* dependencies are used only in Kaoto UI for source code editor in web

chore(deps): remove unused monaco-* dependencies

---

CHANGELOG.md
package.json

Camel 4.11 has introduced `--disable-auto` parameter without checking if the cluster-type has been already set or not.
The automatic detection does not work if connected user cannot list resource "clusterversions" in API group "config.openshift.io" at the cluster scope.
Other better ways that could be done later on:
* remove automatically the --disable-auto when detecting that the version is prior to 4.11
* forget about 4.11 and improve handling these parameters in Camel JBang

Fix deploy on OpenShift by default on restricted environments

---

it-tests/BasicFlow.test.ts

the data-testid for Datamapper step has been modified, it now contains also the path in the structure

Adapt UI test to Kaoto main

---

CHANGELOG.md
src/webview/VSCodeKaotoEditorChannelApi.ts

In order to support setting the VS Code ColorTheme in Kaoto, we need to initialize the SettingsAdapter with the appropriate ColorSchema interpolation.
fix: https://github.com/KaotoIO/kaoto/issues/1543
requires: https://github.com/KaotoIO/kaoto/pull/2118

feat(UI): Support VS Code ColorTheme

---

.vscode/launch.json

for those interested just add into your .bashrc/.zshrc line
`export VSCODE_DISABLE_EXT="--disable-extensions"`

chore: in a dev mode disable other extensions for an Extension Host vscode instance

---

it-tests/settings/CatalogURLSettings.test.ts
package.json

the previous one was deprecated.
Note that the previous one is not compatible with current main version of Kaoto, see https://github.com/KaotoIO/kaoto/issues/2383

Use newer online Catalog repository example

---

CHANGELOG.md
it-tests/vscode-settings-minikube.json
package.json
src/helpers/CamelJBang.ts
src/helpers/helpers.ts

BEFORE:
AFTER:
unfortunately there is no way to have it as before "JBang", after changes in latest vscode versions it displays this weird space 😞

fix: Camel JBang settings title in new vscode version is displayed wrong

---

CHANGELOG.md
README.md
package.json
yarn.lock

Red Hat Developer SandBox is running with VS Code 1.100.3 so we cannot bump minimal version to support also that environment

chore: revert minimal VS Code requirement back to v1.100.x

---

CHANGELOG.md
src/helpers/CamelJBang.ts

which is often the case just after we added a step and that save is hit.
fixes #1093
fixes #1094

Allow to update dependencies on not fully configured route
